sonar.projectKey=Dilki687_order-service
sonar.organization=dilki687

sonar.sources=src
sonar.tests=test
sonar.exclusions=node_modules/**,coverage/**

sonar.sourceEncoding=UTF-8

# Tell SonarCloud where the coverage report is
sonar.javascript.lcov.reportPaths=coverage/lcov.info